### PR TITLE
Add back missing symbols

### PR DESCRIPTION
**Pull request by milkice233**

### CODE REVIEW

**Comment by SakuraSa233** [comment]
What a miss,thanks,,

**Comment by WordlessEcho** [comment]
@SakuraSa233 https://github.com/RikkaApps/FCM-for-Mojo/pull/59/files
Here you could see the changes by pull request.

A `</` loss at line 94.

**Comment by SakuraSa233** [comment]
I have known that.Thanks.
I'm sorry to have a bad pull request without checking the code again.

**Comment by WordlessEcho** [comment]
So, @RikkaW haven't reviewed source **again**.

**Pull request merged**
